# Generated by Django 4.1.5 on 2023-01-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="furnised",
            new_name="furnished",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="room",
            new_name="rooms",
        ),
    ]
