# Generated by Django 4.1.5 on 2023-01-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_rename_furnised_listing_furnished_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="Listing_type",
            new_name="listing_type",
        ),
    ]
